### PR TITLE
week 4

### PR DESCRIPTION
**Pull request by frrf**

### CODE REVIEW

**Review by jdevries3133 — APPROVED** [review]
Looks good! I see nothing to comment on specifically. As a best practice, avoid committing commented-out code. I know this is a course so it's a bit contrived, but in general commented-out code falls out of date quickly and is generally an annoyance. 

Also, I have an extra challenge should you choose to accept: add custom middleware to one of these examples that checks the value in the `Content-Type` header on the incoming request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type). 

If a client is requesting a content type other than `application/json`, send back a response with status code 400 (bad requests), and some message like `Content-Type not supported. application/json is the only supporter content-type`. 

Nice work!

**Review by jdevries3133 — APPROVED** [review]
Everything looks good! Again, I have no specific comments. Please let me know if you have any questions!

Edit: oops! Gotta cleanup my inbox

**Comment by frrf** [comment]
> Looks good! I see nothing to comment on specifically. As a best practice, avoid committing commented-out code. I know this is a course so it's a bit contrived, but in general commented-out code falls out of date quickly and is generally an annoyance.
> 
> Also, I have an extra challenge should you choose to accept: add custom middleware to one of these examples that checks the value in the `Content-Type` header on the incoming request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type).
> 
> If a client is requesting a content type other than `application/json`, send back a response with status code 400 (bad requests), and some message like `Content-Type not supported. application/json is the only supporter content-type`.
> 
> Nice work!

added [here](https://github.com/frrf/node-express-course/blob/84e43a20ba1c5e885efc8b1b4378082414a90071/02-express-tutorial/extraChallengeMiddleware.js)!

**Comment by jdevries3133** [comment]
> > Looks good! I see nothing to comment on specifically. As a best practice, avoid committing commented-out code. I know this is a course so it's a bit contrived, but in general commented-out code falls out of date quickly and is generally an annoyance.
> > Also, I have an extra challenge should you choose to accept: add custom middleware to one of these examples that checks the value in the `Content-Type` header on the incoming request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type).
> > If a client is requesting a content type other than `application/json`, send back a response with status code 400 (bad requests), and some message like `Content-Type not supported. application/json is the only supporter content-type`.
> > Nice work!
> 
> added [here](https://github.com/frrf/node-express-course/blob/84e43a20ba1c5e885efc8b1b4378082414a90071/02-express-tutorial/extraChallengeMiddleware.js)!

Nice work!

**Pull request merged**
